### PR TITLE
Fixes #3

### LINKED ISSUE #3: Contact form don't never send mail
**Describe the bug**
after completing the form the click on the send button toggle the message error... but there are not. It result the mail aren't send.

**To Reproduce**
1. Go to 'contact'
2. Complete the form without error
3. click send

**Expected behavior**
The error will not be trigger and the mail must be sent

### PR DESCRIPTION
**Pull request by Seb6277**
Better error detection. autocompletion from browser does not trigger onChange

### CODE REVIEW

File: client/src/components/contact/ContactFormComponent.js [hunk 1]
```diff
@@ -13,7 +13,8 @@ class ContactFormComponent extends React.Component{
       emailValid: false,
       validMessage: false,
       captchaValid: false,
-      toggleTextError: false
+      toggleTextError: false,
+      toggleMailError: false
```
Comment (Seb6277) [inline client/src/components/contact/ContactFormComponent.js]: Added same error check for mail

File: client/src/components/contact/ContactFormComponent.js [hunk 2]
```diff
@@ -55,11 +56,14 @@ class ContactFormComponent extends React.Component{
...
         })
-    } else {
       // Field are not valid input
-      this.setState({toggleTextError: !this.state.toggleTextError})
+    } else if (!this.state.validMessage && this.state.emailValid) {
+      this.setState({toggleTextError: true})
+    } else if (!this.state.emailValid && this.state.validMessage) {
+      this.setState({toggleMailError: true})
+    } else {
+      this.setState({toggleMailError: true, toggleTextError: true})
```
Comment (Seb6277) [inline client/src/components/contact/ContactFormComponent.js]: Cover all error cases

File: client/src/components/contact/ContactFormComponent.js [hunk 3]
```diff
@@ -74,17 +78,25 @@ class ContactFormComponent extends React.Component{
       textError = null
     }
 
+    let mailError = null;
+    if (this.state.toggleMailError) {
+      mailError = <Label className="textError">Email must contain '@' character.</Label>
+    } else {
+      mailError = null
+    }
+
```
Comment (Seb6277) [inline client/src/components/contact/ContactFormComponent.js]: Create an error message for mail
